---
title: "Operations Research and Optimisation: where to start?"
date: 2020-04-08
---

[[https://en.wikipedia.org/wiki/Operations_research][Operations research]] (OR) is a vast area comprising a lot of theory,
different branches of mathematics, and too many applications to
count. In this post, I will try to explain why I find it so
fascinating, but also why it can be a little disconcerting to explore
at first. Then I will try to ease the newcomer's path in this rich
area, by suggesting a very rough "map" of the field and a few
references to get started.

Keep in mind that although I studied it during my graduate studies,
this is not my primary area of expertise (I'm a data scientist by
trade), and I definitely don't pretend to know everything in OR. This
is a field too vast for any single person to understand in its
entirety, and I talk mostly from a "amateur mathematician and computer
scientist" standpoint.

* Why is it hard to approach?

Operations research can be difficult to approach, since there are many
references and subfields. Compared to machine learning for instance,
OR has a slightly longer history (going back to the 17th century, for
example with Monge and the optimal transport problem). This means that
good textbooks and such have existed for a long time, but also that
there will be plenty of material to choose from.

Moreover, OR is very close to applications. Sometimes methods may vary
a lot in their presentation depending on whether they're applied to
train tracks, sudoku, or travelling salesmen. In practice, the
terminology and notations are not the same everywhere. This is
disconcerting if you are used to mathematics, where notations evolved
over a long time and is pretty much standardised for many areas. In
contrast, if you're used to the statistics literature with its [[https://lingpipe-blog.com/2009/10/13/whats-wrong-with-probability-notation/][strange
notations]], you will find that OR is actually very well formalised.

- why it may be more difficult to approach than other, more recent
  areas like ML and DL
  - slightly longer history
  - always very close to applications: somehow more "messy" in its
    notations, vocabulary, standard references, etc, as other "purer"
    fields of maths (similar to stats in this regard)
  - often approached from a applied point of view means that many very
    different concepts are often mixed together
- why it is interesting and you should pursue it anyway
  - history of the field
  - examples of applications
  - theory perspective, rigorous field
- different subfields
  - optimisation: constrained and unconstrained
  - game theory
  - dynamic programming
  - stochastic processes
  - simulation
- how to learn and practice
  - references
  - courses
  - computational assets
